apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-with-tags
    env: test
  name: deployment-with-tags
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-with-tags
  template:
    metadata:
      labels:
        app: deployment-with-tags
    spec:
      containers:
        - name: kurd
          image: gcr.io/kuar-demo/kuard-amd64:blue
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 2000
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: 256Mi
            limits:
              cpu: "200m"
              memory: 512Mi
