apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: lab-et-self-guided-tour
spec:
  content:
    image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:fd4a98feea12307c86f1e9c5c0e9b0ac6e10d04b980b43aec72d764e770710fe
  description: A guided tour of how to build a workshop for your team's learning center.
  session:
    applications:
      console:
        enabled: true
      docker:
        enabled: true
      editor:
        enabled: true
      examiner:
        enabled: true
      files:
        directory: exercises
        enabled: true
      registry:
        enabled: true
      terminal:
        enabled: true
        layout: split
    ingresses:
      - host: nginx.$(session_namespace).svc.cluster.local
        name: nginx-via-proxy
        port: 8080
        protocol: http
    namespaces:
      budget: small
  title: Workshop Building Tutorial
