apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tko-day1
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  title: Partner Demo Workshop - Module 2
  description: Workshop created to demo the TKO Day 1 operations.
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/Tanzu-Partner-SE/tmc-tko-lc
  content:
    files: github.com/Tanzu-Partner-SE/tmc-tko-lc?ref=main
    image: harbor.mytanzusandbox.com/learningcenter/tko-day1:0.0.5
  session:
    resources:
      storage: 5Gi
      memory: 2Gi
    namespaces:
      #budget: small
      budget: custom
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      docker:
        enabled: true
        memory: 3Gi
        storage: 20Gi

    objects:
      - apiVersion: v1
        kind: LimitRange
        metadata:
          name: resource-limits
        spec:
          limits:
            - max:
                cpu: "4"
                memory: 10Gi
              min:
                cpu: 5m
                memory: 32Mi
              type: Pod
            - default:
                cpu: "2"
                memory: 4Gi
              defaultRequest:
                cpu: 50m
                memory: 128Mi
              max:
                cpu: "4"
                memory: 10Gi
              min:
                cpu: 5m
                memory: 32Mi
              type: Container
            - max:
                storage: 10Gi
              min:
                storage: 1Gi
              type: PersistentVolumeClaim
      - apiVersion: v1
        kind: Service
        metadata:
          labels:
            learningcenter.tanzu.vmware.com/session.name: $(session_namespace)
            app.name: wp
          name: $(session_namespace)-petclinic
          namespace: $(workshop_namespace)
        spec:
          ports:
            - name: 30080-tcp
              port: 30080
              protocol: TCP
              targetPort: 30080
          selector:
            deployment: $(session_namespace)
          type: ClusterIP

      - apiVersion: projectcontour.io/v1
        kind: HTTPProxy
        metadata:
          name: $(session_namespace)-petclinic
          namespace: $(workshop_namespace)
        spec:
          virtualhost:
            fqdn: $(session_namespace)-petclinic.$(ingress_domain)
            tls:
              secretName: wildcard-lc-tls
          routes:
            - conditions:
                - prefix: /
              services:
                - name: $(session_namespace)-petclinic
                  port: 30080
